services:
    #PHP Service
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        restart: unless-stopped
        tty: true
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - zabehaty_native_apis_network

    #Nginx Service
    webserver:
        image: nginx:alpine
        restart: unless-stopped
        tty: true
        ports:
            - "8080:80"
            - "4439:443"
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - zabehaty_native_apis_network

    #MySQL Service
    db:
        image: mysql:latest
        restart: unless-stopped
        tty: true
        ports:
            - "33069:3306"
        environment:
            MYSQL_DATABASE: zabehaty
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
        networks:
            - zabehaty_native_apis_network

    #phpMyAdmin Service
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8081:80"
        environment:
            - PMA_HOST=db
            - PMA_USER=root
            - PMA_PASSWORD=root
            - UPLOAD_LIMIT=600M
        networks:
            - zabehaty_native_apis_network

    #Redis Service
    redis:
        image: redis:alpine
        restart: unless-stopped
        tty: true
        ports:
            - "6379:6379"
        networks:
            - zabehaty_native_apis_network

    #mailhog Service
    mailpit:
        image: "axllent/mailpit:latest"
        restart: unless-stopped
        ports:
            - "1025:1025"
            - "8025:8025"
        networks:
            - zabehaty_native_apis_network

#Networks
networks:
    zabehaty_native_apis_network:
